[package]
name = "game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
engine = { path = "../engine" }
model = { path = "../model" }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
rand = "0.8"
