[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "engine_bin"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.5"
anyhow = "1.0"
log = "0.4"
